---
core:
    num_workers: 100


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "hosts.yaml"
        group_file: "nornir_groups.yaml"
        defaults_file: "nornir_defaults.yaml"
